/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waldo_JNIExample */

#ifndef _Included_com_waldo_JNIExample
#define _Included_com_waldo_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waldo_JNIExample
 * Method:    foo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_waldo_JNIExample_foo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
