/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JVMTIPROF */

#ifndef _Included_JVMTIPROF
#define _Included_JVMTIPROF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JVMTIPROF
 * Method:    onMethodEntry
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JVMTIPROF_onMethodEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JVMTIPROF
 * Method:    onMethodExit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JVMTIPROF_onMethodExit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
